str = 'awesomesauce'

console.log("our string is:")
console.log(str)
console.log("")
console.log("LENGTH")
console.log("str.length returns length of string: ")
console.log(str.length)
console.log("")
console.log("SLICE")
console.log("str.slice(3,7) returns a new string including the first index and excluding the second: ")
console.log(str.slice(3,7))
console.log("str.slice(7) returns a new string including the first index and extending to the end of the array: ")
console.log(str.slice(7))
console.log("the string is not mutated: ")
console.log(str)
console.log("")
console.log("INDEXOF")
console.log("str.indexOf('w') returns the index of the first character matching the argument: ")
console.log(str.indexOf('w'))
console.log("you can also use a series of characters. str.indexOf('sauce') returns the index of the first character matching the argument: ")
console.log(str.indexOf('sauce'))
console.log("the string is not mutated: ")
console.log(str)
console.log("")
console.log("TRIM")
console.log("If we add some spaces and newlines...")
str = '   awesomesauce\n'
console.log(str)
console.log("str.trim() returns string with all newlines, tabs and whitespaces removed: ")
console.log(str.trim())
console.log("the string is not mutated: ")
console.log(str)
console.log("")
console.log("CHARAT")
console.log("I'm going to reset awesomesauce without all those whitespaces")
str = str.trim()
console.log("str.charAt(1) returns the character at the specified index: ")
console.log(str.charAt(1))
console.log("this can also be done as if the string was an array, str[1]: ")
console.log(str[1])
console.log("the string is not mutated: ")
console.log(str)
console.log("")
